### ISSUE TITLE
Interviewing.io isn't accepting new users

### ISSUE THREAD

**Issue by ashwinbhat712** [llSourcell/Programming_Interview_Study_Plan#1]
Hi Siraj,

Thanks for the awesome content.
I tried signing up for interviewing.io, but it appears they are in a private beta-testing phase and aren't accepting any new users at this point. I found an alternate resource called Pramp, that works in a similar fashion (and is free to use). Maybe you'd consider updating your curriculum to add Pramp as an alternative?

**Comment by asamirr** [comment]
Might wanna check out triplebyte.com too.

**Comment by amannayak** [comment]
Check with sudo corporate it will work
